### ISSUE TITLE
vector memory broke app

### ISSUE THREAD

**Issue by Gitnock** [batuhanbilginn/makr-ai#6]
I can't seem to get the app working, I keep getting this error `{
  code: 'PGRST202',
  details: 'Searched for the function public.search_messages with parameters chat_id, match_count, owner_id, query_embedding, similarity_threshold or with a single unnamed json/jsonb parameter, but no matches were found in the schema cache.',
  hint: null,  message: 'Could not find the function public.search_messages(chat_id, match_count, owner_id, query_embedding, similarity_threshold) in the schema cache'}`
every time I try to add a new message.

**Comment by batuhanbilginn** [comment]
Yeah, this is because the new long-term memory feature. I’ll explain today how to setup Supabase with this new feature. Sorry for the inconvenience.

**Comment by batuhanbilginn** [comment]
> Yeah, this is because the new long-term memory feature. I’ll explain today how to setup Supabase with this new feature. Sorry for the inconvenience.

Okay, now I explained how to setup Supabase with new vector search, long-term memory feature. You can it out from the `readme`file.

[Readme.md](https://github.com/batuhanbilginn/makr-ai/blob/main/README.md)

**Comment by Gitnock** [comment]
Thanks so much for the quick response @batuhanbilginn, ok I promise this is my last question🙏, 
I keep getting this error when trying to create a new message: `
{
  code: '42703',
  details: null,
  hint: 'Perhaps you meant to reference the column "a.pair".',
  message: 'column m.pair does not exist'
}
`, I think its related to how I created my messages pair column, but am not completely sure.
![image](https://user-images.githubusercontent.com/33192984/232256353-1b6edcc3-bb9a-47c2-8e42-881003c1a4c4.png)
